title: Meditations
sort_title: Meditations
publication_date: null
description: |
    Meditations (Medieval Greek: Τὰ εἰς ἑαυτόν, romanized: Ta eis heauton,
    literally "things to one's self") is a series of personal writings by Marcus
    Aurelius, Roman Emperor from 161 to 180 AD, recording his private notes to
    himself and ideas on Stoic philosophy.

    Marcus Aurelius wrote the 12 books of the Meditations in Koine Greek as a
    source for his own guidance and self-improvement. It is possible that large
    portions of the work were written at Sirmium, where he spent much time
    planning military campaigns from 170 to 180. Some of it was written while he
    was positioned at Aquincum on campaign in Pannonia, because internal notes
    tell us that the first book was written when he was campaigning against the
    Quadi on the river Granova (modern-day Hron) and the second book was written
    at Carnuntum.

    It is unlikely that Marcus Aurelius ever intended the writings to be
    published and the work has no official title, so "Meditations" is one of
    several titles commonly assigned to the collection. These writings take the
    form of quotations varying in length from one sentence to long paragraphs.
edition:
    primary: true
    title: Thoughts of Marcus Aurelius Antonius
    num: 1
    deepest: 1
    published: 1893-01-01
    translator:
        - name: George Long
          family_name: Long
          birth_date: 1800-11-04
          death_date: 1879-08-10
          description: |
              George Long (November 4, 1800 – August 10, 1879) was an English
              classical scholar.

              Long was born at Poulton-le-Fylde, Lancashire, and educated at
              Macclesfield Grammar School, St John's College, Cambridge and
              later Trinity College, Cambridge.

              He was Craven university scholar in 1821 (bracketed with Lord
              Macaulay and Henry Maiden), wrangler and senior chancellor's
              medallist in 1822 and became a fellow of Trinity in 1823. In 1824
              he was elected professor of ancient languages in the new
              University of Virginia at Charlottesville, but after four years
              returned to England as the first professor of Greek at the newly
              founded University College in London

              In 1842 he succeeded T. H. Key as Professor of Latin at University
              College; in 1846–1849 he was reader in jurisprudence and civil law
              in the Middle Temple, and finally (1849–1871) classical lecturer
              at Brighton College. Subsequently, he lived in retirement at
              Portfield, Chichester, in receipt (from 1873) of a Civil List
              pension of £100 a year obtained for him by Gladstone.

              He was one of the founders (1830), and for twenty years an
              officer, of the Royal Geographical Society; an active member of
              the Society for the Diffusion of Useful Knowledge, for which he
              edited the quarterly Journal of Education (1831–1835) as well as
              many of its text-books; the editor (at first with Charles Knight,
              afterwards alone) of the Penny Cyclopaedia and of Knight's
              Political Dictionary; and a member of the Society for Central
              Education instituted in London in 1837.

              He contributed the Roman law articles to Smith's Dictionary of
              Greek and Roman Antiquities, and wrote also for the companion
              dictionaries of Biography and Geography. He is remembered,
              however, mainly as the editor of the Bibliotheca Classica
              series—the first serious attempt to produce scholarly editions of
              classical texts with English commentaries—to which he contributed
              the edition of Cicero's orations (1851–1862).
    editor:
        - name: Edwin Ginn
          family_name: Ginn
          birth_date: 1838-02-14
          death_date: 1914-01-21
          description: |
              Edwin Ginn (February 14, 1838 – January 21, 1914) was an American
              publisher, peace advocate, and philanthropist.

              Ginn was born in Orland, Maine on February 14, 1838, into a
              Universalist farming family who were descendants of early settlers
              of Maryland, Virginia, and Salem, Massachusetts. He attended
              Westbrook Seminary, a Universalist preparatory school; forgoing
              the ministry, he enrolled instead at Tufts University in 1858. He
              graduated from Tufts with a Bachelor of Arts degree in 1862,
              receiving his Masters of Arts at the same time.

              After graduation, Ginn had a successful career selling
              schoolbooks. In 1868 he founded Ginn & Co., which became a leading
              textbook American publisher. The company was later known as Ginn
              and Heath.

              Ginn married twice, fathering six children. In his late 50s, Ginn
              turned his focus to philanthropy: the American peace movement was his
              primary concern.

              Ginn died on January 21, 1914, at his home in Winchester,
              Massachusetts, after suffering from a paralytic stroke and
              pneumonia a month earlier.[1] A library is named after him at
              Tufts's Fletcher School of Law and Diplomacy.
    author:
        - name: Marcus Aurelius
          family_name: Aurelius
          birth_date: null
          death_date: null
          description: |
              Marcus Aurelius (/ɑːˈriːliəs/ or /ɑːˈriːljəs/;[1] Latin: Marcus
              Aurelius Antoninus Augustus; 26 April 121 – 17 March 180) was
              Roman emperor from 161 to 180 and a Stoic philosopher. He was the
              last of the rulers traditionally known as the Five Good Emperors,
              and the last emperor of the Pax Romana, an age of relative peace
              and stability for the Roman Empire. He served as Roman consul in
              140, 145, and 161.

              The son of the praetor Marcus Annius Verus (III) and the wealthy
              heiress Domitia Lucilla, Marcus was raised by his grandfather,
              Marcus Annius Verus (II), after his father died. His uncle,
              Antoninus Pius, adopted him shortly before becoming emperor in
              138. Now heir to the throne, Marcus studied Greek and Latin under
              tutors such as Herodes Atticus and Marcus Cornelius Fronto. He
              kept in close correspondence with Fronto for many years
              afterwards. Marcus married Antoninus' daughter Faustina in 145.
              Antoninus died following an illness in 161.

              The reign of Marcus Aurelius was marked by military conflict. In
              the East, the Roman Empire fought successfully with a revitalized
              Parthian Empire and the rebel Kingdom of Armenia. Marcus defeated
              the Marcomanni, Quadi, and Sarmatian Iazyges in the Marcomannic
              Wars; however, these and other Germanic peoples began to represent
              a troubling reality for the Empire. He modified the silver purity
              of the Roman currency, the denarius. The persecution of Christians
              in the Roman Empire is believed to have increased during his
              reign. The Antonine Plague broke out in 165 or 166 and devastated
              the population of the Roman Empire, causing the deaths of five
              million people.

              Marcus never adopted an heir unlike some of his predecessors; his
              children included Lucilla (who married Lucius Verus, co-emperor
              from 161 to 169) and Commodus, whose succession after Marcus has
              become a subject of debate among both contemporary and modern
              historians. The Column and Equestrian Statue of Marcus Aurelius
              still stand in Rome, where they were erected in celebration of his
              military victories. Meditations, the writings of 'the philosopher'
              – as contemporary biographers called Marcus, are a significant
              source of the modern understanding of ancient Stoic philosophy.
              They have been praised by fellow writers, philosophers, monarchs,
              and politicians centuries after his death.
    description: null
