title: King Lear
sort_title: King Lear
publication_date: 1606-01-01
description: |
    Dramatis Personæ
    ================

    LEAR, King of Britain.  
    GONERIL, eldest daughter to Lear.  
    REGAN, second daughter to Lear.  
    CORDELIA, youngest daughter to Lear.  
    DUKE of ALBANY, married to Goneril.  
    DUKE of CORNWALL, married to Regan.  
    KING of FRANCE.  
    DUKE of BURGUNDY.  
    EARL of GLOUCESTER.  
    EDGAR, elder son to Gloucester.  
    EDMUND, younger bastard son to Gloucester.  
    EARL of KENT.  
    FOOL.  
    OSWALD, steward to Goneril.  
    CURAN, a Courtier.  
    OLD MAN, Tenant to Gloucester.  
    Physician.  
    An Officer employed by Edmund.  
    Gentleman, attendant on Cordelia.  
    A Herald.  
    Servants to Cornwall.

    Knights attending on the King, Officers, Messengers, Soldiers and
    Attendants.

    SCENE: Britain.
    ---------------

    From Wikipedia
    ==============

    King Lear is a tragedy written by William Shakespeare. It depicts the
    gradual descent into madness of the title character, after he disposes of
    his kingdom by bequeathing his power and land to two of his three daughters
    in exchange for insincere declarations of love, bringing tragic consequences
    for all. Derived from the legend of Leir of Britain, a mythological
    pre-Roman Celtic king, the play has been widely adapted for the stage and
    motion pictures, with the title role coveted by many of the world’s most
    accomplished actors.

    The first attribution to Shakespeare of this play, originally drafted in
    1605 or 1606 at the latest with its first known performance on St. Stephen’s
    Day in 1606, was a 1608 publication in a quarto of uncertain provenance, in
    which the play is listed as a history; it may be an early draft or simply
    reflect the first performance text. The Tragedy of King Lear, a more
    theatrical revision, was included in the 1623 First Folio. Modern editors
    usually conflate the two, though some insist that each version has its own
    individual integrity that should be preserved.

    After the English Restoration, the play was often revised with a happy,
    non-tragic ending for audiences who disliked its dark and depressing tone,
    but since the 19th century Shakespeare’s original version has been regarded
    as one of his supreme achievements. The tragedy is particularly noted for
    its probing observations on the nature of human suffering and kinship.
    George Bernard Shaw wrote, “No man will ever write a better tragedy than
    Lear.”
edition:
    primary: true
    title: PG's First Folio King Lear
    verse: true
    number: 1
    publication_date: 1623-01-01
    description: |
        The modern text of King Lear derives from three sources: two quartos,
        published in 1608 (Q1) and 1619 (Q2) respectively, and the version in
        the First Folio of 1623 (F1). The differences between these versions are
        significant. Q1 contains 285 lines not in F1; F1 contains around 100
        lines not in Q1. Also, at least a thousand individual words are changed
        between the two texts, each text has a completely different style of
        punctuation, and about half the verse lines in the F1 are either printed
        as prose or differently divided in the Q1. The early editors, beginning
        with Alexander Pope, simply conflated the two texts, creating the modern
        version that has remained nearly universal for centuries. The conflated
        version is born from the hypothesis that Shakespeare wrote only one
        original manuscript, now unfortunately lost, and that the Quarto and
        Folio versions are distortions of that original. Others, such as Nuttall
        and Bloom, have identified Shakespeare himself as having been involved
        in reworking passages in the play to accommodate performances and other
        textual requirements of the play.
    translator: []
    editor: []
    author:
        - name: William Shakespeare
          family_name: Shakespeare
          birth_date: 1616-04-26
          death_date: 1616-04-23
          description: |
              From Wikipedia
              ==============

              William Shakespeare (bapt. 26 April 1564 – 23 April 1616) was an
              English poet, playwright and actor, widely regarded as the
              greatest writer in the English language and the world’s greatest
              dramatist. He is often called England’s national poet and the
              “Bard of Avon”. His extant works, including collaborations,
              consist of approximately 39 plays, 154 sonnets, two long narrative
              poems, and a few other verses, some of uncertain authorship. His
              plays have been translated into every major living language and
              are performed more often than those of any other playwright.

              Shakespeare was born and raised in Stratford-upon-Avon,
              Warwickshire. At the age of 18, he married Anne Hathaway, with
              whom he had three children: Susanna and twins Hamnet and Judith.
              Sometime between 1585 and 1592, he began a successful career in
              London as an actor, writer, and part-owner of a playing company
              called the Lord Chamberlain’s Men, later known as the King’s Men.
              At age 49 (around 1613), he appears to have retired to Stratford,
              where he died three years later. Few records of Shakespeare’s
              private life survive; this has stimulated considerable speculation
              about such matters as his physical appearance, his sexuality, his
              religious beliefs, and whether the works attributed to him were
              written by others. Such theories are often criticised for failing
              to adequately note that few records survive of most commoners of
              the period.

              Shakespeare produced most of his known works between 1589 and
              1613. His early plays were primarily comedies and histories and
              are regarded as some of the best work produced in these genres.
              Until about 1608, he wrote mainly tragedies, among them Hamlet,
              Othello, King Lear, and Macbeth, all considered to be among the
              finest works in the English language. In the last phase of his
              life, he wrote tragicomedies (also known as romances) and
              collaborated with other playwrights.

              Many of Shakespeare’s plays were published in editions of varying
              quality and accuracy in his lifetime. However, in 1623, two fellow
              actors and friends of Shakespeare’s, John Heminges and Henry
              Condell, published a more definitive text known as the First
              Folio, a posthumous collected edition of Shakespeare’s dramatic
              works that included all but two of his plays. The volume was
              prefaced with a poem by Ben Jonson, in which Jonson presciently
              hails Shakespeare in a now-famous quote as “not of an age, but for
              all time”.

              Throughout the 20th and 21st centuries, Shakespeare’s works have
              been continually adapted and rediscovered by new movements in
              scholarship and performance. His plays remain popular and are
              studied, performed, and reinterpreted through various cultural and
              political contexts around the world.
