description: 'King Lear is a tragedy written by William Shakespeare. It depicts the
  gradual descent into madness of the title character, after he disposes of his kingdom
  by bequeathing his power and land to two of his three daughters in exchange for
  insincere declarations of love, bringing tragic consequences for all. Derived from
  the legend of Leir of Britain, a mythological pre-Roman Celtic king, the play has
  been widely adapted for the stage and motion pictures, with the title role coveted
  by many of the world''s most accomplished actors.

  The first attribution to Shakespeare of this play, originally drafted in 1605 or
  1606 at the latest with its first known performance on St. Stephen''s Day in 1606,
  was a 1608 publication in a quarto of uncertain provenance, in which the play is
  listed as a history; it may be an early draft or simply reflect the first performance
  text. The Tragedy of King Lear, a more theatrical revision, was included in the
  1623 First Folio. Modern editors usually conflate the two, though some insist that
  each version has its own individual integrity that should be preserved.

  After the English Restoration, the play was often revised with a happy, non-tragic
  ending for audiences who disliked its dark and depressing tone, but since the 19th
  century Shakespeare''s original version has been regarded as one of his supreme
  achievements. The tragedy is particularly noted for its probing observations on
  the nature of human suffering and kinship. George Bernard Shaw wrote, "No man will
  ever write a better tragedy than Lear."'
edition:
  author:
  - birth_date: 1564-04-26
    death_date: 1616-04-23
    description: "From Wikipedia\n==============\n\nWilliam Shakespeare (bapt. 26\
      \ April 1564 \u2013 23 April 1616) was an\nEnglish poet, playwright and actor,\
      \ widely regarded as the\ngreatest writer in the English language and the world\u2019\
      s greatest\ndramatist. He is often called England\u2019s national poet and the\n\
      \u201CBard of Avon\u201D. His extant works, including collaborations,\nconsist\
      \ of approximately 39 plays, 154 sonnets, two long narrative\npoems, and a few\
      \ other verses, some of uncertain authorship. His\nplays have been translated\
      \ into every major living language and\nare performed more often than those\
      \ of any other playwright.\n\nShakespeare was born and raised in Stratford-upon-Avon,\n\
      Warwickshire. At the age of 18, he married Anne Hathaway, with\nwhom he had\
      \ three children: Susanna and twins Hamnet and Judith.\nSometime between 1585\
      \ and 1592, he began a successful career in\nLondon as an actor, writer, and\
      \ part-owner of a playing company\ncalled the Lord Chamberlain\u2019s Men, later\
      \ known as the King\u2019s Men.\nAt age 49 (around 1613), he appears to have\
      \ retired to Stratford,\nwhere he died three years later. Few records of Shakespeare\u2019\
      s\nprivate life survive; this has stimulated considerable speculation\nabout\
      \ such matters as his physical appearance, his sexuality, his\nreligious beliefs,\
      \ and whether the works attributed to him were\nwritten by others. Such theories\
      \ are often criticised for failing\nto adequately note that few records survive\
      \ of most commoners of\nthe period.\n\nShakespeare produced most of his known\
      \ works between 1589 and\n1613. His early plays were primarily comedies and\
      \ histories and\nare regarded as some of the best work produced in these genres.\n\
      Until about 1608, he wrote mainly tragedies, among them Hamlet,\nOthello, King\
      \ Lear, and Macbeth, all considered to be among the\nfinest works in the English\
      \ language. In the last phase of his\nlife, he wrote tragicomedies (also known\
      \ as romances) and\ncollaborated with other playwrights.\n\nMany of Shakespeare\u2019\
      s plays were published in editions of varying\nquality and accuracy in his lifetime.\
      \ However, in 1623, two fellow\nactors and friends of Shakespeare\u2019s, John\
      \ Heminges and Henry\nCondell, published a more definitive text known as the\
      \ First\nFolio, a posthumous collected edition of Shakespeare\u2019s dramatic\n\
      works that included all but two of his plays. The volume was\nprefaced with\
      \ a poem by Ben Jonson, in which Jonson presciently\nhails Shakespeare in a\
      \ now-famous quote as \u201Cnot of an age, but for\nall time\u201D.\n\nThroughout\
      \ the 20th and 21st centuries, Shakespeare\u2019s works have\nbeen continually\
      \ adapted and rediscovered by new movements in\nscholarship and performance.\
      \ His plays remain popular and are\nstudied, performed, and reinterpreted through\
      \ various cultural and\npolitical contexts around the world.\n"
    family_name: Shakespeare
    name: William Shakespeare
  deepest: 2
  description: ''
  editor: []
  num: 1
  primary: true
  published: 1623-01-01
  translator: []
  verse: true
publication_date: 1623-01-01
sort_title: King Lear
title: King Lear
