title: Sense and Sensibility
sort_title: Sense and Sensibility
publication_date: 1811-01-01
description: |
    Sense and Sensibility is a novel by Jane Austen, published in 1811. It was
    published anonymously; By A Lady appears on the title page where the
    author's name might have been. It tells the story of the Dashwood sisters,
    Elinor (age 19) and Marianne (age 16 1/2) as they come of age. They have an
    older half-brother, John, and a younger sister, Margaret, 13.

    The novel follows the three Dashwood sisters as they must move with their
    widowed mother from the estate on which they grew up, Norland Park. Because
    Norland is passed down to John, the product of Mr. Dashwood's first
    marriage, and his young son, the four Dashwood women need to look for a new
    home. They have the opportunity to rent a modest home, Barton Cottage, on
    the property of a distant relative, Sir John Middleton. There they
    experience love, romance, and heartbreak. The novel is likely set in
    southwest England, London, and Sussex between 1792 and 1797.

    The novel, which sold out its first print run of 750 copies in the middle of
    1813, marked a success for its author. It had a second print run later that
    year. It was the first Austen title to be republished in England after her
    death, and the first illustrated Austen produced in Britain, in Richard
    Bentley's Standard Novels series of 1833. The novel continued in publication
    throughout the 19th, 20th and early 21st centuries and has many times been
    illustrated, excerpted, abridged, and adapted for stage and film.
edition:
    primary: true
    title: null
    num: 1
    deepest: 1
    published: 1811-01-01
    description: null
    translator: []
    editor: []
    author:
        - name: Jane Austen
          family_name: Austen
          birth_date: 1775-12-16
          death_date: 1817-07-18
          description: |
              Jane Austen (/ˈɒstɪn, ˈɔːs-/; 16 December 1775 – 18 July 1817) was
              an English novelist known primarily for her six major novels,
              which interpret, critique and comment upon the British landed
              gentry at the end of the 18th century. Austen's plots often
              explore the dependence of women on marriage in the pursuit of
              favourable social standing and economic security. Her works
              critique the novels of sensibility of the second half of the 18th
              century and are part of the transition to 19th-century literary
              realism. Her use of biting irony, along with her realism, humour,
              and social commentary, have long earned her acclaim among critics,
              scholars, and popular audiences alike.

              With the publications of Sense and Sensibility (1811), Pride and
              Prejudice (1813), Mansfield Park (1814) and Emma (1816), she
              achieved success as a published writer. She wrote two additional
              novels, Northanger Abbey and Persuasion, both published
              posthumously in 1818, and began another, eventually titled
              Sanditon, but died before its completion. She also left behind
              three volumes of juvenile writings in manuscript, a short
              epistolary novel Lady Susan, and another unfinished novel, The
              Watsons. Her six full-length novels have rarely been out of print,
              although they were published anonymously and brought her moderate
              success and little fame during her lifetime.

              A significant transition in her posthumous reputation occurred in
              1833, when her novels were republished in Richard Bentley's
              Standard Novels series, illustrated by Ferdinand Pickering, and
              sold as a set. They gradually gained wider acclaim and popular
              readership. In 1869, fifty-two years after her death, her nephew's
              publication of A Memoir of Jane Austen introduced a compelling
              version of her writing career and supposedly uneventful life to an
              eager audience.

              Austen has inspired many critical essays and literary anthologies.
              Her novels have inspired many films, from 1940's Pride and
              Prejudice to more recent productions like Sense and Sensibility
              (1995), Emma (1996), Mansfield Park (1999), Pride & Prejudice
              (2005), and Love & Friendship (2016).
