description: 'Romeo and Juliet is a tragedy written by William Shakespeare early in
  his career about two young star-crossed lovers whose deaths ultimately reconcile
  their feuding families. It was among Shakespeare''s most popular plays during his
  lifetime and along with Hamlet, is one of his most frequently performed plays. Today,
  the title characters are regarded as archetypal young lovers.

  Romeo and Juliet belongs to a tradition of tragic romances stretching back to antiquity.  The
  plot is based on an Italian tale translated into verse as The Tragical History of
  Romeus and Juliet by Arthur Brooke in 1562 and retold in prose in Palace of Pleasure
  by William Painter in 1567. Shakespeare borrowed heavily from both but expanded
  the plot by developing a number of supporting characters, particularly Mercutio
  and Paris. Believed to have been written between 1591 and 1595, the play was first
  published in a quarto version in 1597. The text of the first quarto version was
  of poor quality, however, and later editions corrected the text to conform more
  closely with Shakespeare''s original.

  Shakespeare''s use of his poetic dramatic structure (especially effects such as
  switching between comedy and tragedy to heighten tension, his expansion of minor
  characters, and his use of sub-plots to embellish the story) has been praised as
  an early sign of his dramatic skill. The play ascribes different poetic forms to
  different characters, sometimes changing the form as the character develops. Romeo,
  for example, grows more adept at the sonnet over the course of the play.

  Romeo and Juliet has been adapted numerous times for stage, film, musical, and opera
  venues. During the English Restoration, it was revived and heavily revised by William
  Davenant. David Garrick''s 18th-century version also modified several scenes, removing
  material then considered indecent, and Georg Benda''s Romeo und Julie omitted much
  of the action and added a happy ending. Performances in the 19th century, including
  Charlotte Cushman''s, restored the original text and focused on greater realism.
  John Gielgud''s 1935 version kept very close to Shakespeare''s text and used Elizabethan
  costumes and staging to enhance the drama. In the 20th and into the 21st century,
  the play has been adapted in versions as diverse as George Cukor''s 1936 film Romeo
  and Juliet, Franco Zeffirelli''s 1968 version Romeo and Juliet, and Baz Luhrmann''s
  1996 MTV-inspired Romeo + Juliet.'
edition:
  author:
  - birth_date: 1564-04-26
    death_date: 1616-04-23
    description: "From Wikipedia\n==============\n\nWilliam Shakespeare (bapt. 26\
      \ April 1564 \u2013 23 April 1616) was an\nEnglish poet, playwright and actor,\
      \ widely regarded as the\ngreatest writer in the English language and the world\u2019\
      s greatest\ndramatist. He is often called England\u2019s national poet and the\n\
      \u201CBard of Avon\u201D. His extant works, including collaborations,\nconsist\
      \ of approximately 39 plays, 154 sonnets, two long narrative\npoems, and a few\
      \ other verses, some of uncertain authorship. His\nplays have been translated\
      \ into every major living language and\nare performed more often than those\
      \ of any other playwright.\n\nShakespeare was born and raised in Stratford-upon-Avon,\n\
      Warwickshire. At the age of 18, he married Anne Hathaway, with\nwhom he had\
      \ three children: Susanna and twins Hamnet and Judith.\nSometime between 1585\
      \ and 1592, he began a successful career in\nLondon as an actor, writer, and\
      \ part-owner of a playing company\ncalled the Lord Chamberlain\u2019s Men, later\
      \ known as the King\u2019s Men.\nAt age 49 (around 1613), he appears to have\
      \ retired to Stratford,\nwhere he died three years later. Few records of Shakespeare\u2019\
      s\nprivate life survive; this has stimulated considerable speculation\nabout\
      \ such matters as his physical appearance, his sexuality, his\nreligious beliefs,\
      \ and whether the works attributed to him were\nwritten by others. Such theories\
      \ are often criticised for failing\nto adequately note that few records survive\
      \ of most commoners of\nthe period.\n\nShakespeare produced most of his known\
      \ works between 1589 and\n1613. His early plays were primarily comedies and\
      \ histories and\nare regarded as some of the best work produced in these genres.\n\
      Until about 1608, he wrote mainly tragedies, among them Hamlet,\nOthello, King\
      \ Lear, and Macbeth, all considered to be among the\nfinest works in the English\
      \ language. In the last phase of his\nlife, he wrote tragicomedies (also known\
      \ as romances) and\ncollaborated with other playwrights.\n\nMany of Shakespeare\u2019\
      s plays were published in editions of varying\nquality and accuracy in his lifetime.\
      \ However, in 1623, two fellow\nactors and friends of Shakespeare\u2019s, John\
      \ Heminges and Henry\nCondell, published a more definitive text known as the\
      \ First\nFolio, a posthumous collected edition of Shakespeare\u2019s dramatic\n\
      works that included all but two of his plays. The volume was\nprefaced with\
      \ a poem by Ben Jonson, in which Jonson presciently\nhails Shakespeare in a\
      \ now-famous quote as \u201Cnot of an age, but for\nall time\u201D.\n\nThroughout\
      \ the 20th and 21st centuries, Shakespeare\u2019s works have\nbeen continually\
      \ adapted and rediscovered by new movements in\nscholarship and performance.\
      \ His plays remain popular and are\nstudied, performed, and reinterpreted through\
      \ various cultural and\npolitical contexts around the world.\n"
    family_name: Shakespeare
    name: William Shakespeare
  deepest: 2
  description: ''
  editor: []
  num: 1
  primary: true
  published: 1623-01-01
  translator: []
  verse: true
publication_date: 1623-01-01
sort_title: Romeo and Juliet
title: Romeo and Juliet
