description: "The Tragedy of Hamlet, Prince of Denmark, often shortened to Hamlet\
  \ (), is a tragedy written by William Shakespeare sometime between 1599 and 1602.\
  \ Set in Denmark, the play depicts Prince Hamlet and his revenge against his uncle,\
  \ Claudius, who has murdered Hamlet's father in order to seize his throne and marry\
  \ Hamlet's mother.\nHamlet is Shakespeare's longest play and is considered among\
  \ the most powerful and influential works of world literature, with a story capable\
  \ of \"seemingly endless retelling and adaptation by others\". It was one of Shakespeare's\
  \ most popular works during his lifetime and still ranks among his most performed,\
  \ topping the performance list of the Royal Shakespeare Company and its predecessors\
  \ in Stratford-upon-Avon since 1879. It has inspired many other writers\u2014from\
  \ Johann Wolfgang von Goethe and Charles Dickens to James Joyce and Iris Murdoch\u2014\
  and has been described as \"the world's most filmed story after Cinderella\".The\
  \ story of Shakespeare's Hamlet was derived from the legend of Amleth, preserved\
  \ by 13th-century chronicler Saxo Grammaticus in his Gesta Danorum, as subsequently\
  \ retold by the 16th-century scholar Fran\xE7ois de Belleforest.  Shakespeare may\
  \ also have drawn on an earlier Elizabethan play known today as the Ur-Hamlet, though\
  \ some scholars believe Shakespeare wrote the Ur-Hamlet, later revising it to create\
  \ the version of Hamlet we now have. He almost certainly wrote his version of the\
  \ title role for his fellow actor, Richard Burbage, the leading tragedian of Shakespeare's\
  \ time. In the 400 years since its inception, the role has been performed by numerous\
  \ highly acclaimed actors in each successive century.\nThree different early versions\
  \ of the play are extant: the First Quarto (Q1, 1603); the Second Quarto (Q2, 1604);\
  \ and the First Folio (F1, 1623). Each version includes lines and entire scenes\
  \ missing from the others. The play's structure and depth of characterisation have\
  \ inspired much critical scrutiny. One such example is the centuries-old debate\
  \ about Hamlet's hesitation to kill his uncle, which some see as merely a plot device\
  \ to prolong the action but which others argue is a dramatisation of the complex\
  \ philosophical and ethical issues that surround cold-blooded murder, calculated\
  \ revenge, and thwarted desire. More recently, psychoanalytic critics have examined\
  \ Hamlet's unconscious desires, while feminist critics have re-evaluated and attempted\
  \ to rehabilitate the often-maligned characters of Ophelia and Gertrude."
edition:
  author:
  - birth_date: 1564-04-26
    death_date: 1616-04-23
    description: "From Wikipedia\n==============\n\nWilliam Shakespeare (bapt. 26\
      \ April 1564 \u2013 23 April 1616) was an\nEnglish poet, playwright and actor,\
      \ widely regarded as the\ngreatest writer in the English language and the world\u2019\
      s greatest\ndramatist. He is often called England\u2019s national poet and the\n\
      \u201CBard of Avon\u201D. His extant works, including collaborations,\nconsist\
      \ of approximately 39 plays, 154 sonnets, two long narrative\npoems, and a few\
      \ other verses, some of uncertain authorship. His\nplays have been translated\
      \ into every major living language and\nare performed more often than those\
      \ of any other playwright.\n\nShakespeare was born and raised in Stratford-upon-Avon,\n\
      Warwickshire. At the age of 18, he married Anne Hathaway, with\nwhom he had\
      \ three children: Susanna and twins Hamnet and Judith.\nSometime between 1585\
      \ and 1592, he began a successful career in\nLondon as an actor, writer, and\
      \ part-owner of a playing company\ncalled the Lord Chamberlain\u2019s Men, later\
      \ known as the King\u2019s Men.\nAt age 49 (around 1613), he appears to have\
      \ retired to Stratford,\nwhere he died three years later. Few records of Shakespeare\u2019\
      s\nprivate life survive; this has stimulated considerable speculation\nabout\
      \ such matters as his physical appearance, his sexuality, his\nreligious beliefs,\
      \ and whether the works attributed to him were\nwritten by others. Such theories\
      \ are often criticised for failing\nto adequately note that few records survive\
      \ of most commoners of\nthe period.\n\nShakespeare produced most of his known\
      \ works between 1589 and\n1613. His early plays were primarily comedies and\
      \ histories and\nare regarded as some of the best work produced in these genres.\n\
      Until about 1608, he wrote mainly tragedies, among them Hamlet,\nOthello, King\
      \ Lear, and Macbeth, all considered to be among the\nfinest works in the English\
      \ language. In the last phase of his\nlife, he wrote tragicomedies (also known\
      \ as romances) and\ncollaborated with other playwrights.\n\nMany of Shakespeare\u2019\
      s plays were published in editions of varying\nquality and accuracy in his lifetime.\
      \ However, in 1623, two fellow\nactors and friends of Shakespeare\u2019s, John\
      \ Heminges and Henry\nCondell, published a more definitive text known as the\
      \ First\nFolio, a posthumous collected edition of Shakespeare\u2019s dramatic\n\
      works that included all but two of his plays. The volume was\nprefaced with\
      \ a poem by Ben Jonson, in which Jonson presciently\nhails Shakespeare in a\
      \ now-famous quote as \u201Cnot of an age, but for\nall time\u201D.\n\nThroughout\
      \ the 20th and 21st centuries, Shakespeare\u2019s works have\nbeen continually\
      \ adapted and rediscovered by new movements in\nscholarship and performance.\
      \ His plays remain popular and are\nstudied, performed, and reinterpreted through\
      \ various cultural and\npolitical contexts around the world.\n"
    family_name: Shakespeare
    name: William Shakespeare
  description: ''
  editor: []
  number: 1
  primary: true
  publication_date: 1623-01-01
  translator: []
  verse: true
publication_date: 1623-01-01
sort_title: Hamlet
title: Hamlet
