description: "Troilus and Cressida () is a tragedy by William Shakespeare, believed\
  \ to have been written in 1602. It was described by Frederick S. Boas as one of\
  \ Shakespeare's problem plays. The play ends on a very bleak note with the death\
  \ of the noble Trojan Hector and destruction of the love between Troilus and Cressida.\
  \ The work has in recent years \"stimulated exceptionally lively critical debate\"\
  .Throughout the play, the tone lurches wildly between bawdy comedy and tragic gloom,\
  \ and readers and theatre-goers have frequently found it difficult to understand\
  \ how one is meant to respond to the characters. Several characteristic elements\
  \ of the play (the most notable being its constant questioning of intrinsic values\
  \ such as hierarchy, honour and love) have often been viewed as distinctly \"modern\"\
  , as in the following remarks on the play by author and literary scholar Joyce Carol\
  \ Oates:\n\nTroilus and Cressida, that most vexing and ambiguous of Shakespeare's\
  \ plays, strikes the modern reader as a contemporary document \u2013 its investigation\
  \ of numerous infidelities, its criticism of tragic pretensions, above all, its\
  \ implicit debate between what is essential in human life and what is only existential\
  \ are themes of the twentieth century. ... This is tragedy of a special sort \u2013\
  \ the \"tragedy\" the basis of which is the impossibility of conventional tragedy."
edition:
  author:
  - birth_date: 1564-04-26
    death_date: 1616-04-23
    description: "From Wikipedia\n==============\n\nWilliam Shakespeare (bapt. 26\
      \ April 1564 \u2013 23 April 1616) was an\nEnglish poet, playwright and actor,\
      \ widely regarded as the\ngreatest writer in the English language and the world\u2019\
      s greatest\ndramatist. He is often called England\u2019s national poet and the\n\
      \u201CBard of Avon\u201D. His extant works, including collaborations,\nconsist\
      \ of approximately 39 plays, 154 sonnets, two long narrative\npoems, and a few\
      \ other verses, some of uncertain authorship. His\nplays have been translated\
      \ into every major living language and\nare performed more often than those\
      \ of any other playwright.\n\nShakespeare was born and raised in Stratford-upon-Avon,\n\
      Warwickshire. At the age of 18, he married Anne Hathaway, with\nwhom he had\
      \ three children: Susanna and twins Hamnet and Judith.\nSometime between 1585\
      \ and 1592, he began a successful career in\nLondon as an actor, writer, and\
      \ part-owner of a playing company\ncalled the Lord Chamberlain\u2019s Men, later\
      \ known as the King\u2019s Men.\nAt age 49 (around 1613), he appears to have\
      \ retired to Stratford,\nwhere he died three years later. Few records of Shakespeare\u2019\
      s\nprivate life survive; this has stimulated considerable speculation\nabout\
      \ such matters as his physical appearance, his sexuality, his\nreligious beliefs,\
      \ and whether the works attributed to him were\nwritten by others. Such theories\
      \ are often criticised for failing\nto adequately note that few records survive\
      \ of most commoners of\nthe period.\n\nShakespeare produced most of his known\
      \ works between 1589 and\n1613. His early plays were primarily comedies and\
      \ histories and\nare regarded as some of the best work produced in these genres.\n\
      Until about 1608, he wrote mainly tragedies, among them Hamlet,\nOthello, King\
      \ Lear, and Macbeth, all considered to be among the\nfinest works in the English\
      \ language. In the last phase of his\nlife, he wrote tragicomedies (also known\
      \ as romances) and\ncollaborated with other playwrights.\n\nMany of Shakespeare\u2019\
      s plays were published in editions of varying\nquality and accuracy in his lifetime.\
      \ However, in 1623, two fellow\nactors and friends of Shakespeare\u2019s, John\
      \ Heminges and Henry\nCondell, published a more definitive text known as the\
      \ First\nFolio, a posthumous collected edition of Shakespeare\u2019s dramatic\n\
      works that included all but two of his plays. The volume was\nprefaced with\
      \ a poem by Ben Jonson, in which Jonson presciently\nhails Shakespeare in a\
      \ now-famous quote as \u201Cnot of an age, but for\nall time\u201D.\n\nThroughout\
      \ the 20th and 21st centuries, Shakespeare\u2019s works have\nbeen continually\
      \ adapted and rediscovered by new movements in\nscholarship and performance.\
      \ His plays remain popular and are\nstudied, performed, and reinterpreted through\
      \ various cultural and\npolitical contexts around the world.\n"
    family_name: Shakespeare
    name: William Shakespeare
  deepest: 2
  description: ''
  editor: []
  num: 1
  primary: true
  published: 1623-01-01
  translator: []
  verse: true
publication_date: 1623-01-01
sort_title: Troilus and Cressida
title: Troilus and Cressida
