description: 'The Taming of the Shrew is a comedy by William Shakespeare, believed
  to have been written between 1590 and 1592.

  The play begins with a framing device, often referred to as the induction, in which
  a mischievous nobleman tricks a drunken tinker named Christopher Sly into believing
  he is actually a nobleman himself. The nobleman then has the play performed for
  Sly''s diversion.

  The main plot depicts the courtship of Petruchio and Katherina, the headstrong,
  obdurate shrew. Initially, Katherina is an unwilling participant in the relationship;
  however, Petruchio "tames" her with various psychological torments, such as keeping
  her from eating and drinking, until she becomes a desirable, compliant, and obedient
  bride. The subplot features a competition between the suitors of Katherina''s younger
  sister, Bianca, who is seen as the "ideal" woman. The question of whether the play
  is misogynistic or not has become the subject of considerable controversy, particularly
  among modern scholars, audiences, and readers.

  The Taming of the Shrew has been adapted numerous times for stage, screen, opera,
  ballet, and musical theatre; perhaps the most famous adaptations being Cole Porter''s
  Kiss Me, Kate and the 1967 film of the play, starring Elizabeth Taylor and Richard
  Burton. The 1999 high school comedy film 10 Things I Hate About You is also loosely
  based on the play.'
edition:
  author:
  - birth_date: 1564-04-26
    death_date: 1616-04-23
    description: "From Wikipedia\n==============\n\nWilliam Shakespeare (bapt. 26\
      \ April 1564 \u2013 23 April 1616) was an\nEnglish poet, playwright and actor,\
      \ widely regarded as the\ngreatest writer in the English language and the world\u2019\
      s greatest\ndramatist. He is often called England\u2019s national poet and the\n\
      \u201CBard of Avon\u201D. His extant works, including collaborations,\nconsist\
      \ of approximately 39 plays, 154 sonnets, two long narrative\npoems, and a few\
      \ other verses, some of uncertain authorship. His\nplays have been translated\
      \ into every major living language and\nare performed more often than those\
      \ of any other playwright.\n\nShakespeare was born and raised in Stratford-upon-Avon,\n\
      Warwickshire. At the age of 18, he married Anne Hathaway, with\nwhom he had\
      \ three children: Susanna and twins Hamnet and Judith.\nSometime between 1585\
      \ and 1592, he began a successful career in\nLondon as an actor, writer, and\
      \ part-owner of a playing company\ncalled the Lord Chamberlain\u2019s Men, later\
      \ known as the King\u2019s Men.\nAt age 49 (around 1613), he appears to have\
      \ retired to Stratford,\nwhere he died three years later. Few records of Shakespeare\u2019\
      s\nprivate life survive; this has stimulated considerable speculation\nabout\
      \ such matters as his physical appearance, his sexuality, his\nreligious beliefs,\
      \ and whether the works attributed to him were\nwritten by others. Such theories\
      \ are often criticised for failing\nto adequately note that few records survive\
      \ of most commoners of\nthe period.\n\nShakespeare produced most of his known\
      \ works between 1589 and\n1613. His early plays were primarily comedies and\
      \ histories and\nare regarded as some of the best work produced in these genres.\n\
      Until about 1608, he wrote mainly tragedies, among them Hamlet,\nOthello, King\
      \ Lear, and Macbeth, all considered to be among the\nfinest works in the English\
      \ language. In the last phase of his\nlife, he wrote tragicomedies (also known\
      \ as romances) and\ncollaborated with other playwrights.\n\nMany of Shakespeare\u2019\
      s plays were published in editions of varying\nquality and accuracy in his lifetime.\
      \ However, in 1623, two fellow\nactors and friends of Shakespeare\u2019s, John\
      \ Heminges and Henry\nCondell, published a more definitive text known as the\
      \ First\nFolio, a posthumous collected edition of Shakespeare\u2019s dramatic\n\
      works that included all but two of his plays. The volume was\nprefaced with\
      \ a poem by Ben Jonson, in which Jonson presciently\nhails Shakespeare in a\
      \ now-famous quote as \u201Cnot of an age, but for\nall time\u201D.\n\nThroughout\
      \ the 20th and 21st centuries, Shakespeare\u2019s works have\nbeen continually\
      \ adapted and rediscovered by new movements in\nscholarship and performance.\
      \ His plays remain popular and are\nstudied, performed, and reinterpreted through\
      \ various cultural and\npolitical contexts around the world.\n"
    family_name: Shakespeare
    name: William Shakespeare
  description: ''
  editor: []
  number: 1
  primary: true
  publication_date: 1623-01-01
  translator: []
  verse: true
publication_date: 1623-01-01
sort_title: Taming of the Shrew
title: The Taming of the Shrew
