title: Metamorphoses
sort_title: Metamorphoses
publication_date: 8-01-01
description: |
    The Metamorphoses (Latin: Metamorphōseōn librī: "Books of Transformations")
    is a Latin narrative poem by the Roman poet Ovid, considered his magnum
    opus. Comprising 11,995 lines, 15 books and over 250 myths, the poem
    chronicles the history of the world from its creation to the deification of
    Julius Caesar within a loose mythico-historical framework.

    Although meeting the criteria for an epic, the poem defies simple genre
    classification by its use of varying themes and tones. Ovid took inspiration
    from the genre of metamorphosis poetry, and some of the Metamorphoses
    derives from earlier treatment of the same myths; however, he diverged
    significantly from all of his models.

    One of the most influential works in Western culture, the Metamorphoses has
    inspired such authors as Dante Alighieri, Giovanni Boccaccio, Geoffrey
    Chaucer, and William Shakespeare. Numerous episodes from the poem have been
    depicted in acclaimed works of sculpture, painting, and music. Although
    interest in Ovid faded after the Renaissance, there was a resurgence of
    attention to his work towards the end of the 20th century. Today the
    Metamorphoses continues to inspire and be retold through various media. The
    work has been the subject of numerous translations into English, the first
    by William Caxton in 1480.
edition:
    primary: true
    title: null
    num: 1
    deepest: 2
    published: 1893-01-01
    translator:
        - name: Henry T. Riley
          family_name: Riley
          birth_date: 1816-06-01
          death_date: 1878-04-14
          description: |
              Henry Thomas Riley (1816–1878) was an English translator,
              lexicographer, and antiquary.

              Born in June 1816, he was only son of Henry Riley of Southwark, an
              ironmonger. He was educated at Chatham House, Ramsgate, and at
              Charterhouse School (1832–4). He entered Trinity College,
              Cambridge, but at the end of his first term migrated to Clare
              College where he was admitted on 17 December 1834, and elected a
              scholar on 24 January 1835. In 1838 he obtained a Latin essay
              prize. He graduated B.A. in 1840 and M.A. in 1859, after which he
              moved to Corpus Christi College. On 16 June 1870 he was
              incorporated at Exeter College, Oxford.

              Riley was called to the bar at the Inner Temple on 23 November
              1847, but early in life he began hack work for booksellers to make
              a living, by editing and translation. On the creation of the
              Historical Manuscripts Commission (by royal charter in April
              1869), Riley was engaged as an additional inspector for England,
              and given the task of examining the archives of various municipal
              corporations, the muniments of the colleges at Oxford and
              Cambridge, and the documents in the registries of various bishops
              and chapters.

              Riley died at Hainault House, the Crescent, Selhurst, Croydon, on
              14 April 1878, aged 61.
    editor: []
    author:
        - name: Ovid
          family_name: Ovid
          birth_date: null
          death_date: null
          description: |
              Publius Ovidius Naso (Classical Latin: [ˈpu:.blɪ.ʊs ɔˈwɪ.dɪ.ʊs
              ˈnaː.soː]; 20 March 43 BC – 17/18 AD), known as Ovid (/ˈɒvɪd/)
              in the English-speaking world, was a Roman poet who lived during
              the reign of Augustus. He was a contemporary of the older Virgil
              and Horace, with whom he is often ranked as one of the three
              canonical poets of Latin literature. The Imperial scholar
              Quintilian considered him the last of the Latin love elegists.
              He enjoyed enormous popularity, but, in one of the mysteries of
              literary history, was sent by Augustus into exile in a remote
              province on the Black Sea, where he remained until his death. Ovid
              himself attributes his exile to carmen et error, "a poem and a
              mistake", but his discretion in discussing the causes has resulted
              in much speculation among scholars.

              The first major Roman poet to begin his career during the reign of
              Augustus, Ovid is today best known for the Metamorphoses, a
              15-book continuous mythological narrative written in the meter of
              epic, and for works in elegiac couplets such as Ars Amatoria ("The
              Art of Love") and Fasti. His poetry was much imitated during Late
              Antiquity and the Middle Ages, and greatly influenced Western art
              and literature. The Metamorphoses remains one of the most
              important sources of classical mythology.
    description: null
