description: "From Wikipedia\n==============\n\nShakespeare\u2019s sonnets are poems\
  \ that William Shakespeare wrote on a variety\nof themes. When discussing or referring\
  \ to Shakespeare\u2019s sonnets, it is\nalmost always a reference to the 154 sonnets\
  \ that were first published all\ntogether in a quarto in 1609; however there are\
  \ six additional sonnets that\nShakespeare wrote and included in the plays Romeo\
  \ and Juliet, Henry V and\nLove\u2019s Labour\u2019s Lost.\n"
edition:
  author:
  - birth_date: 1616-04-26
    death_date: 1616-04-23
    description: "From Wikipedia\n==============\n\nWilliam Shakespeare (bapt. 26\
      \ April 1564 \u2013 23 April 1616) was an\nEnglish poet, playwright and actor,\
      \ widely regarded as the\ngreatest writer in the English language and the world\u2019\
      s greatest\ndramatist. He is often called England\u2019s national poet and the\n\
      \u201CBard of Avon\u201D. His extant works, including collaborations,\nconsist\
      \ of approximately 39 plays, 154 sonnets, two long narrative\npoems, and a few\
      \ other verses, some of uncertain authorship. His\nplays have been translated\
      \ into every major living language and\nare performed more often than those\
      \ of any other playwright.\n\nShakespeare was born and raised in Stratford-upon-Avon,\n\
      Warwickshire. At the age of 18, he married Anne Hathaway, with\nwhom he had\
      \ three children: Susanna and twins Hamnet and Judith.\nSometime between 1585\
      \ and 1592, he began a successful career in\nLondon as an actor, writer, and\
      \ part-owner of a playing company\ncalled the Lord Chamberlain\u2019s Men, later\
      \ known as the King\u2019s Men.\nAt age 49 (around 1613), he appears to have\
      \ retired to Stratford,\nwhere he died three years later. Few records of Shakespeare\u2019\
      s\nprivate life survive; this has stimulated considerable speculation\nabout\
      \ such matters as his physical appearance, his sexuality, his\nreligious beliefs,\
      \ and whether the works attributed to him were\nwritten by others. Such theories\
      \ are often criticised for failing\nto adequately note that few records survive\
      \ of most commoners of\nthe period.\n\nShakespeare produced most of his known\
      \ works between 1589 and\n1613. His early plays were primarily comedies and\
      \ histories and\nare regarded as some of the best work produced in these genres.\n\
      Until about 1608, he wrote mainly tragedies, among them Hamlet,\nOthello, King\
      \ Lear, and Macbeth, all considered to be among the\nfinest works in the English\
      \ language. In the last phase of his\nlife, he wrote tragicomedies (also known\
      \ as romances) and\ncollaborated with other playwrights.\n\nMany of Shakespeare\u2019\
      s plays were published in editions of varying\nquality and accuracy in his lifetime.\
      \ However, in 1623, two fellow\nactors and friends of Shakespeare\u2019s, John\
      \ Heminges and Henry\nCondell, published a more definitive text known as the\
      \ First\nFolio, a posthumous collected edition of Shakespeare\u2019s dramatic\n\
      works that included all but two of his plays. The volume was\nprefaced with\
      \ a poem by Ben Jonson, in which Jonson presciently\nhails Shakespeare in a\
      \ now-famous quote as \u201Cnot of an age, but for\nall time\u201D.\n\nThroughout\
      \ the 20th and 21st centuries, Shakespeare\u2019s works have\nbeen continually\
      \ adapted and rediscovered by new movements in\nscholarship and performance.\
      \ His plays remain popular and are\nstudied, performed, and reinterpreted through\
      \ various cultural and\npolitical contexts around the world.\n"
    family_name: Shakespeare
    name: William Shakespeare
  deepest: 2
  description: "The primary source of Shakespeare\u2019s sonnets is a quarto published\
    \ in\n1609 titled Shake-speare\u2019s Sonnets. It contains 154 sonnets, which\
    \ are\nfollowed by the long poem \u201CA Lover\u2019s Complaint\u201D. Thirteen\
    \ copies of the\nquarto have survived in fairly good shape from the 1609 edition,\
    \ which\nis the only edition; there were no other printings. There is evidence\
    \ in\na note on the title page of one of the extant copies that the great\nElizabethan\
    \ actor Edward Alleyn bought a copy in June 1609 for one\nshilling.\n\nThe sonnets\
    \ cover such themes as the passage of time, love, infidelity,\njealousy, beauty\
    \ and mortality. The first 126 are addressed to a young\nman; the last 28 are\
    \ either addressed to, or refer to a woman. (Sonnets\n138 and 144 had previously\
    \ been published in the 1599 miscellany The\nPassionate Pilgrim).\n\nThe title\
    \ of the quarto, Shakespeare\u2019s Sonnets, is consistent with the\nentry in\
    \ the Stationer Register. The title appears in upper case\nlettering on the title\
    \ page, where it is followed by the phrase \u201CNeuer\nbefore Imprinted\u201D\
    . The title also appears every time the quarto is\nopened. That the author\u2019\
    s name in a possessive form is part of the title\nsets it apart from all other\
    \ sonnet collections of the time, except for\none \u2014 Sir Philip Sidney\u2019\
    s posthumous 1591 publication that is titled,\nSyr. P.S. his Astrophel and Stella,\
    \ which is considered one of\nShakespeare\u2019s most important models. Sidney\u2019\
    s title may have inspired\nShakespeare, particularly if the \u201CW.H.\u201D of\
    \ Shakespeare\u2019s dedication is\nSidney\u2019s nephew and heir, William Herbert.\
    \ The idea that the persona\nreferred to as the speaker of the Shakespeare\u2019\
    s sonnets might be\nShakespeare himself, is aggressively repudiated by scholars,\
    \ however,\nthe title of the quarto does seem to encourage that kind of\nspeculation.\n\
    \nThe first 17 poems, traditionally called the procreation sonnets, are\naddressed\
    \ to the young man \u2013 urging him to marry and have children in\norder to immortalize\
    \ his beauty by passing it to the next generation.\nOther sonnets express the\
    \ speaker\u2019s love for the young man; brood upon\nloneliness, death, and the\
    \ transience of life; seem to criticise the\nyoung man for preferring a rival\
    \ poet; express ambiguous feelings for\nthe speaker\u2019s mistress; and pun on\
    \ the poet\u2019s name. The final two\nsonnets are allegorical treatments of Greek\
    \ epigrams referring to the\n\u201Clittle love-god\u201D Cupid.\n\nThe publisher,\
    \ Thomas Thorpe, entered the book in the Stationers\u2019\nRegister on 20 May\
    \ 1609:\n\n> Tho. Thorpe. Entred for his copie under the handes of master Wilson\n\
    > and master Lownes Wardenes a booke called Shakespeares sonnettes vjd.\n\nWhether\
    \ Thorpe used an authorised manuscript from Shakespeare or an\nunauthorised copy\
    \ is unknown. George Eld printed the quarto, and the run\nwas divided between\
    \ the booksellers William Aspley and John Wright.\n"
  editor: []
  num: 1
  primary: true
  published: 1609-01-01
  title: null
  translator: []
  verse: true
publication_date: 1869-01-01
sort_title: Sonnets
title: The Sonnets
