title: Pride and Prejudice
sort_title: Pride and Prejudice
publication_date: 1813-01-28
description: |
    Pride and Prejudice is an 1813 romantic novel of manners written by Jane
    Austen. The novel follows the character development of Elizabeth Bennet, the
    dynamic protagonist of the book, who learns about the repercussions of hasty
    judgments and eventually comes to appreciate the difference between
    superficial goodness and actual goodness. A classic piece filled with
    comedy, its humour lies in its honest depiction of manners, education,
    marriage and money during the Regency era in Great Britain.

    Mr Bennet of Longbourn estate has five daughters, but because his property
    is entailed it can only be passed from male heir to male heir. Consequently,
    Mr Bennet's family will be destitute upon his death. Because his wife also
    lacks an inheritance, it is imperative that at least one of the girls marry
    well to support the others upon his death, which is a motivation that drives
    the plot. Jane Austen's opening line--"It is a truth universally
    acknowledged, that a single man in possession of a good fortune, must be in
    want of a wife"—is a sentence filled with irony and sets the tone for the
    book. The novel revolves around the importance of marrying for love, not
    simply for economic gain or social prestige, despite the communal pressure
    to make a good (i.e., wealthy) match.

    Pride and Prejudice has delighted readers for years, consistently appearing
    near the top of lists of "most-loved books" among literary scholars and the
    reading public. It has become one of the most popular novels in English
    literature with over 20 million copies sold and has inspired many
    derivatives that abound in modern literature. For more than a century,
    amateur and professional dramatic adaptations, reprints, unofficial sequels,
    films, and TV versions of Pride and Prejudice have portrayed the memorable
    characters and themes of the novel, reaching mass audiences. The 2005
    film Pride & Prejudice, starring Keira Knightley and Matthew Macfadyen, is
    the most recent film adaptation that closely represents the book, with the
    2016 action, comedy, and horror spin-off Pride and Prejudice and Zombies
    being the most recent Hollywood film adaptation.
edition:
    primary: true
    title: null
    num: 1
    deepest: 1
    published: 1813-01-28
    description: null
    translator: []
    editor: []
    author:
        - name: Jane Austen
          family_name: Austen
          birth_date: 1775-12-16
          death_date: 1817-07-18
          description: |
              Jane Austen (/ˈɒstɪn, ˈɔːs-/; 16 December 1775 – 18 July 1817) was
              an English novelist known primarily for her six major novels,
              which interpret, critique and comment upon the British landed
              gentry at the end of the 18th century. Austen's plots often
              explore the dependence of women on marriage in the pursuit of
              favourable social standing and economic security. Her works
              critique the novels of sensibility of the second half of the 18th
              century and are part of the transition to 19th-century literary
              realism. Her use of biting irony, along with her realism, humour,
              and social commentary, have long earned her acclaim among critics,
              scholars, and popular audiences alike.

              With the publications of Sense and Sensibility (1811), Pride and
              Prejudice (1813), Mansfield Park (1814) and Emma (1816), she
              achieved success as a published writer. She wrote two additional
              novels, Northanger Abbey and Persuasion, both published
              posthumously in 1818, and began another, eventually titled
              Sanditon, but died before its completion. She also left behind
              three volumes of juvenile writings in manuscript, a short
              epistolary novel Lady Susan, and another unfinished novel, The
              Watsons. Her six full-length novels have rarely been out of print,
              although they were published anonymously and brought her moderate
              success and little fame during her lifetime.

              A significant transition in her posthumous reputation occurred in
              1833, when her novels were republished in Richard Bentley's
              Standard Novels series, illustrated by Ferdinand Pickering, and
              sold as a set. They gradually gained wider acclaim and popular
              readership. In 1869, fifty-two years after her death, her nephew's
              publication of A Memoir of Jane Austen introduced a compelling
              version of her writing career and supposedly uneventful life to an
              eager audience.

              Austen has inspired many critical essays and literary anthologies.
              Her novels have inspired many films, from 1940's Pride and
              Prejudice to more recent productions like Sense and Sensibility
              (1995), Emma (1996), Mansfield Park (1999), Pride & Prejudice
              (2005), and Love & Friendship (2016).
